"""add_station_tasks

Revision ID: 04454bcd162d
Revises: d33140546a64
Create Date: 2025-10-04 11:32:09.396617

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '04454bcd162d'
down_revision: Union[str, Sequence[str], None] = 'd33140546a64'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('station_tasks',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('type', sa.Enum('BATTERY_SWAP', name='stationtasktype'), nullable=False),
    sa.Column('status', sa.Enum('UNASSIGNED', 'ASSIGNED', 'IN_PROGRESS', 'COMPLETED', 'ABANDONED', name='taskstatus'), nullable=False),
    sa.Column('date_created', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.Column('date_updated', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.Column('station_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['station_id'], ['stations.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_station_tasks_id'), 'station_tasks', ['id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_station_tasks_id'), table_name='station_tasks')
    op.drop_table('station_tasks')
    # ### end Alembic commands ###
