"""add_traffic_csv_data_to_sim_instances

Revision ID: 09bfae8f09b5
Revises: 9ee6c9922a25
Create Date: 2026-02-20 09:42:04.213020

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '09bfae8f09b5'
down_revision: Union[str, Sequence[str], None] = '9ee6c9922a25'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('sim_instances', sa.Column('traffic_csv_data', sa.Text(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('sim_instances', 'traffic_csv_data')
    # ### end Alembic commands ###
