"""rename_dispatched_to_in_progress_in_taskstatus_enum

Revision ID: 2436c56e65c2
Revises: 25d76b9be827
Create Date: 2025-10-15 10:23:09.364287

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '2436c56e65c2'
down_revision: Union[str, Sequence[str], None] = '25d76b9be827'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.execute("ALTER TYPE taskstatus RENAME VALUE 'DISPATCHED' TO 'IN_PROGRESS';")
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.execute("ALTER TYPE taskstatus RENAME VALUE 'IN_PROGRESS' TO 'DISPATCHED';")
    # ### end Alembic commands ###
