"""update_station_task_status_enum

Revision ID: 25d76b9be827
Revises: ae69c02d06d8
Create Date: 2025-10-14 16:50:35.022038

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '25d76b9be827'
down_revision: Union[str, Sequence[str], None] = 'ae69c02d06d8'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.execute("ALTER TYPE taskstatus RENAME TO taskstatus_old;")
    op.execute("""
        CREATE TYPE taskstatus AS ENUM ('OPEN', 'ASSIGNED', 'DISPATCHED', 'CLOSED');
    """)
    op.execute("""
        ALTER TABLE station_tasks
        ALTER COLUMN status TYPE taskstatus
        USING LOWER(status::text)::taskstatus;
    """)
    op.execute("DROP TYPE taskstatus_old;")
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.execute("ALTER TYPE taskstatus RENAME TO taskstatus_new;")
    op.execute("""
        CREATE TYPE taskstatus AS ENUM (
            'UNASSIGNED', 'ASSIGNED', 'IN_PROGRESS', 'COMPLETED', 'ABANDONED'
        );
    """)
    op.execute("""
        ALTER TABLE station_tasks
        ALTER COLUMN status TYPE taskstatus
        USING UPPER(status::text)::taskstatus;
    """)
    op.execute("DROP TYPE taskstatus_new;")
    # ### end Alembic commands ###
