"""add_traffic_templates_table

Revision ID: 70e3a53d2e2e
Revises: a27cf78bb7b2
Create Date: 2026-03-25 08:21:52.413985

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '70e3a53d2e2e'
down_revision: Union[str, Sequence[str], None] = 'a27cf78bb7b2'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('traffic_templates',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('key', sa.String(length=32), nullable=False),
    sa.Column('content', sa.Text(), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('date_created', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.Column('date_updated', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_traffic_templates_id'), 'traffic_templates', ['id'], unique=False)
    op.create_index(op.f('ix_traffic_templates_key'), 'traffic_templates', ['key'], unique=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_traffic_templates_key'), table_name='traffic_templates')
    op.drop_index(op.f('ix_traffic_templates_id'), table_name='traffic_templates')
    op.drop_table('traffic_templates')
    # ### end Alembic commands ###
