"""add_user_is_enabled

Revision ID: 729bd5cfd4fc
Revises: 25d76b9be827
Create Date: 2025-10-15 17:35:34.066972

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '729bd5cfd4fc'
down_revision: Union[str, Sequence[str], None] = '2436c56e65c2'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # Manually changed to add default to true for existing users
    op.add_column('users', sa.Column('is_enabled', sa.Boolean(), nullable=False, server_default=sa.true()))


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('users', 'is_enabled')
    # ### end Alembic commands ###
