"""add_sim_instance_id_to_models

Revision ID: 8f170126dde9
Revises: 729bd5cfd4fc
Create Date: 2025-10-25 02:10:05.283750

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '8f170126dde9'
down_revision: Union[str, Sequence[str], None] = '729bd5cfd4fc'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('resources', sa.Column('sim_instance_id', sa.Integer(), nullable=False))
    op.create_foreign_key(None, 'resources', 'sim_instances', ['sim_instance_id'], ['id'])
    op.add_column('station_tasks', sa.Column('sim_instance_id', sa.Integer(), nullable=False))
    op.create_foreign_key(None, 'station_tasks', 'sim_instances', ['sim_instance_id'], ['id'])
    op.add_column('stations', sa.Column('sim_instance_id', sa.Integer(), nullable=False))
    op.create_foreign_key(None, 'stations', 'sim_instances', ['sim_instance_id'], ['id'])
    # Add indexes on sim_instance_id for query performance
    op.create_index('idx_resources_sim_instance_id', 'resources', ['sim_instance_id'])
    op.create_index('idx_station_tasks_sim_instance_id', 'station_tasks', ['sim_instance_id'])
    op.create_index('idx_stations_sim_instance_id', 'stations', ['sim_instance_id'])
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # Drop indexes on sim_instance_id first
    op.drop_index('idx_resources_sim_instance_id', table_name='resources')
    op.drop_index('idx_station_tasks_sim_instance_id', table_name='station_tasks')
    op.drop_index('idx_stations_sim_instance_id', table_name='stations')
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'stations', type_='foreignkey')
    op.drop_column('stations', 'sim_instance_id')
    op.drop_constraint(None, 'station_tasks', type_='foreignkey')
    op.drop_column('station_tasks', 'sim_instance_id')
    op.drop_constraint(None, 'resources', type_='foreignkey')
    op.drop_column('resources', 'sim_instance_id')
    # ### end Alembic commands ###
