"""add_uuid_to_sim_instances_and_sim_keyframes_table

Revision ID: 90070ebfe1c8
Revises: 77374ce4f9cf
Create Date: 2025-12-19 12:41:30.469594

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql


# revision identifiers, used by Alembic.
revision: str = '90070ebfe1c8'
down_revision: Union[str, Sequence[str], None] = '77374ce4f9cf'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('sim_keyframes',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('sim_instance_id', sa.Integer(), nullable=False),
    sa.Column('sim_seconds_elapsed', sa.Float(), nullable=False),
    sa.Column('frame_data', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['sim_instance_id'], ['sim_instances.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('ix_sim_keyframes_created_at', 'sim_keyframes', ['created_at'], unique=False)
    op.create_index(op.f('ix_sim_keyframes_id'), 'sim_keyframes', ['id'], unique=False)
    op.create_index('ix_sim_keyframes_instance_time', 'sim_keyframes', ['sim_instance_id', 'sim_seconds_elapsed'], unique=False)
    op.drop_index(op.f('idx_resources_sim_instance_id'), table_name='resources')
    op.add_column('sim_instances', sa.Column('uuid', sa.String(length=36), nullable=True))
    op.create_index(op.f('ix_sim_instances_uuid'), 'sim_instances', ['uuid'], unique=True)
    op.drop_index(op.f('idx_station_tasks_sim_instance_id'), table_name='station_tasks')
    op.drop_index(op.f('idx_stations_sim_instance_id'), table_name='stations')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_index(op.f('idx_stations_sim_instance_id'), 'stations', ['sim_instance_id'], unique=False)
    op.create_index(op.f('idx_station_tasks_sim_instance_id'), 'station_tasks', ['sim_instance_id'], unique=False)
    op.drop_index(op.f('ix_sim_instances_uuid'), table_name='sim_instances')
    op.drop_column('sim_instances', 'uuid')
    op.create_index(op.f('idx_resources_sim_instance_id'), 'resources', ['sim_instance_id'], unique=False)
    op.drop_index('ix_sim_keyframes_instance_time', table_name='sim_keyframes')
    op.drop_index(op.f('ix_sim_keyframes_id'), table_name='sim_keyframes')
    op.drop_index('ix_sim_keyframes_created_at', table_name='sim_keyframes')
    op.drop_table('sim_keyframes')
    # ### end Alembic commands ###
