"""Add completed field to SimInstance

Revision ID: 95b3268a07a0
Revises: 504983637b01
Create Date: 2026-01-20 15:30:13.435551

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '95b3268a07a0'
down_revision: Union[str, Sequence[str], None] = '504983637b01'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('sim_instances', sa.Column('completed', sa.Boolean(), server_default='false', nullable=False))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('sim_instances', 'completed')
    # ### end Alembic commands ###
