"""Add completed field to SimInstance

Revision ID: 9ee6c9922a25
Revises: 26a3f05ecd67
Create Date: 2026-01-21 18:48:56.045000

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '9ee6c9922a25'
down_revision: Union[str, Sequence[str], None] = '26a3f05ecd67'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('sim_instances', sa.Column('completed', sa.Boolean(), server_default='false', nullable=False))
    op.drop_index(op.f('ix_sim_instances_parent_id'), table_name='sim_instances')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_index(op.f('ix_sim_instances_parent_id'), 'sim_instances', ['parent_sim_instance_id'], unique=False)
    op.drop_column('sim_instances', 'completed')
    # ### end Alembic commands ###
