"""add_resources

Revision ID: ae69c02d06d8
Revises: b92a9d455219
Create Date: 2025-10-10 11:35:41.938457

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'ae69c02d06d8'
down_revision: Union[str, Sequence[str], None] = 'b92a9d455219'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('resources',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('type', sa.Enum('VEHICLE_DRIVER', name='resourcetype'), nullable=False),
    sa.Column('date_created', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.Column('date_updated', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.Column('latitude', sa.Float(), nullable=False),
    sa.Column('longitude', sa.Float(), nullable=False),
    sa.Column('route_start_latitude', sa.Float(), nullable=False),
    sa.Column('route_start_longitude', sa.Float(), nullable=False),
    sa.Column('route_end_latitude', sa.Float(), nullable=False),
    sa.Column('route_end_longitude', sa.Float(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_resources_id'), 'resources', ['id'], unique=False)
    op.add_column('station_tasks', sa.Column('resource_id', sa.Integer(), nullable=True))
    op.create_foreign_key(None, 'station_tasks', 'resources', ['resource_id'], ['id'], ondelete='SET NULL')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'station_tasks', type_='foreignkey')
    op.drop_column('station_tasks', 'resource_id')
    op.drop_index(op.f('ix_resources_id'), table_name='resources')
    op.drop_table('resources')
    # ### end Alembic commands ###
