"""
MIT License

Copyright (c) 2025 VeloSim Contributors

Permission is hereby granted, free of charge, to any person obtaining a copy
of this software and associated documentation files (the "Software"), to deal
in the Software without restriction, including without limitation the rights
to use, copy, modify, merge, publish, distribute, sublicense, and/or sell
copies of the Software, and to permit persons to whom the Software is
furnished to do so, subject to the following conditions:

The above copyright notice and this permission notice shall be included in all
copies or substantial portions of the Software.

THE SOFTWARE IS PROVIDED "AS IS", WITHOUT WARRANTY OF ANY KIND, EXPRESS OR
IMPLIED, INCLUDING BUT NOT LIMITED TO THE WARRANTIES OF MERCHANTABILITY,
FITNESS FOR A PARTICULAR PURPOSE AND NONINFRINGEMENT. IN NO EVENT SHALL THE
AUTHORS OR COPYRIGHT HOLDERS BE LIABLE FOR ANY CLAIM, DAMAGES OR OTHER
LIABILITY, WHETHER IN AN ACTION OF CONTRACT, TORT OR OTHERWISE, ARISING FROM,
OUT OF OR IN CONNECTION WITH THE SOFTWARE OR THE USE OR OTHER DEALINGS IN THE
SOFTWARE.
"""

from datetime import datetime
from typing import Dict, List, Any, Set, Optional
import re
from pydantic import BaseModel, ValidationError, model_validator, field_validator

from sim.entities.inputParameters import InputParameter
from sim.entities.station import Station
from sim.entities.resource import Resource
from sim.entities.driver import Driver
from sim.entities.vehicle import Vehicle
from sim.entities.BatterySwapTask import BatterySwapTask
from sim.entities.position import Position
from sim.utils.base_parse_strategy import BaseParseStrategy


# ==============================================================================
# Pydantic Validation Models
# ==============================================================================


class PositionValidator(BaseModel):
    """Validator for geographical position coordinates."""

    lat: float
    lon: float

    @model_validator(mode="before")
    def check_lat_lon(cls, values: Any) -> Dict[str, float]:
        """Validate and normalize position coordinates.

        Accepts position data as either a dict with lat/lon keys or a list/tuple
        of [lon, lat] and validates that coordinates are within valid ranges.

        Args:
            values: Position data as dict, list, or tuple.

        Returns:
            Dictionary with validated 'lat' and 'lon' keys.

        Raises:
            ValueError: If position format is invalid or coordinates are out of range.
        """
        if isinstance(values, (list, tuple)):
            if len(values) != 2:
                raise ValueError(
                    "Position must contain exactly two coordinates [lon, lat]"
                )
            values = {"lon": float(values[0]), "lat": float(values[1])}
        elif not isinstance(values, dict):
            raise ValueError("Position must be a dict or list/tuple")

        lat = float(values["lat"])
        lon = float(values["lon"])

        if not (-90 <= lat <= 90) or not (-180 <= lon <= 180):
            raise ValueError(f"Invalid latitude/longitude range: {lat}, {lon}")
        return {"lat": lat, "lon": lon}


class ResourceValidator(BaseModel):
    """Validator for resource entity data."""

    resource_id: int
    resource_position: PositionValidator


class StationValidator(BaseModel):
    """Validator for station entity data."""

    station_id: int
    station_name: str
    station_position: PositionValidator


class TaskValidator(BaseModel):
    """Validator for task entity data."""

    id: str | None = None
    station_id: int
    time: str | None = None

    @model_validator(mode="before")
    @classmethod
    def reject_task_id(cls, values: Any) -> Dict[str, Any]:
        """Reject task IDs if provided, as they are auto-generated.

        Args:
            values: Task data as dict.

        Returns:
            Task data dict if 'id' is not present.

        Raises:
            ValueError: If 'id' field is present in task data.
        """
        if isinstance(values, dict) and "id" in values:
            raise ValueError(
                "Task 'id' field is not allowed. "
                "Task IDs are auto-generated by the simulator."
            )
        return values  # type: ignore[no-any-return]

    @field_validator("time", mode="before")
    @classmethod
    def parse_time(cls, v: Any) -> str | None:
        """Parse time to validate valid format.

        Supports: Simple time strings with relative day value (e.g., "day1:08:00")

        Simulator expects:
        - None or omitted for initial_tasks (spawns immediately)
        - Simple time strings with relative day value for scheduled_tasks
        (e.g., "day1:08:00")

        Args:
            v: Time value to validate, either string or None.

        Returns:
            Validated time string or None.

        Raises:
            ValueError: If time format is invalid.
        """
        if isinstance(v, str):
            try:
                daytime_str = v.split(":", 1)
                if daytime_str[0] == v:
                    raise Exception(f"Invalid time format: {v}.")
                day_str = daytime_str[0]
                time_str = daytime_str[1]

                # validate day_str
                pattern = r"^day\d+$"
                if re.match(pattern, day_str, re.IGNORECASE) is None:
                    raise Exception(
                        f"Invalid time format due provided day {day_str} in {v}."
                    )

                # validate time_str
                try:
                    datetime.strptime(time_str, "%H:%M").time()
                except Exception:
                    raise Exception(
                        f"Invalid time format due provided time {time_str} in {v}."
                    )
            except Exception as e:
                raise ValueError(
                    f"""{e} Retry by using a relative day number
                    and simple time format (e.g. 'day1:08:00')"""
                )
            return v
        else:
            raise ValueError(f"Time must be a string or None, got {type(v)}")


class ScenarioTimes(BaseModel):
    """Validator for scenario start and end times."""

    start_time: str
    end_time: str

    @field_validator("start_time", "end_time", mode="before")
    @classmethod
    def parse_time(cls, v: Any) -> str:
        """Parse time to validate valid format.

        Supports: Simple time strings with relative day value (e.g., "day1:08:00")

        Args:
            v: Time value to validate as a string.

        Returns:
            Validated time string.

        Raises:
            ValueError: If time format is invalid.
        """
        if isinstance(v, str):
            try:
                daytime_str = v.split(":", 1)
                if daytime_str[0] == v:
                    raise Exception(f"Invalid time format: {v}.")
                day_str = daytime_str[0]
                time_str = daytime_str[1]

                # validate day_str
                pattern = r"^day\d+$"
                if re.match(pattern, day_str, re.IGNORECASE) is None:
                    raise Exception(
                        f"Invalid time format due provided day {day_str} in {v}."
                    )

                # validate time_str
                try:
                    datetime.strptime(time_str, "%H:%M").time()
                except Exception:
                    raise Exception(
                        f"Invalid time format due provided time {time_str} in {v}."
                    )
                return v
            except Exception as e:
                raise ValueError(
                    f"""{e} Retry by using a relative day number
                    and simple time format (e.g. 'day1:08:00')"""
                )
        else:
            raise ValueError(f"Time must be a string, got {type(v)}")


# ==============================================================================
# Internal Validator Class
# ==============================================================================


class _ScenarioValidator:
    """Internal validator for scenario content.

    This class is an implementation detail. Use JsonParseStrategy instead.
    """

    def __init__(self, json_string: Optional[str] = None) -> None:
        """Initialize validator with optional JSON string for line number tracking.

        Args:
            json_string: Optional JSON string to build line number mapping
                for error reporting.
        """
        self.line_map: Dict[str, int] = {}
        if json_string:
            self._build_line_map(json_string)

    def _build_line_map(self, json_string: str) -> None:
        """Build a map of JSON paths to line numbers.

        Args:
            json_string: JSON string to parse for line number mapping.
        """
        lines = json_string.split("\n")
        path_stack: List[str] = []
        array_counters: Dict[str, int] = {}
        in_array: Dict[str, bool] = {}

        for line_num, line in enumerate(lines, start=1):
            # Track arrays starting
            key_array_match = re.search(r'"([^"]+)"\s*:\s*\[', line)
            if key_array_match:
                key = key_array_match.group(1)
                current_path = ".".join(path_stack + [key]) if path_stack else key
                self.line_map[current_path] = line_num
                array_counters[current_path] = 0
                in_array[current_path] = True
                if "[" in line and "]" not in line:
                    path_stack.append(key)
                continue

            # Track keys in objects
            key_match = re.search(r'"([^"]+)"\s*:', line)
            if key_match:
                key = key_match.group(1)
                # Build the current path
                current_path = ".".join(path_stack + [key]) if path_stack else key
                self.line_map[current_path] = line_num

                # For fields inside arrays, also map with array index
                if path_stack:
                    parent_path = ".".join(path_stack)
                    if parent_path in in_array and in_array[parent_path]:
                        array_idx = array_counters.get(parent_path, 0)
                        indexed_path = f"{parent_path}[{array_idx}].{key}"
                        self.line_map[indexed_path] = line_num

                # Track if we're entering an object
                if "{" in line and "[" not in line and "}" not in line:
                    path_stack.append(key)

            # Detect array element start
            if re.match(r"^\s*\{\s*$", line) and path_stack:
                parent_path = ".".join(path_stack)
                if parent_path in in_array and in_array[parent_path]:
                    array_idx = array_counters[parent_path]
                    element_path = f"{parent_path}[{array_idx}]"
                    self.line_map[element_path] = line_num

            # Pop from stack when closing
            if "}" in line and path_stack:
                parent_path = ".".join(path_stack)
                if parent_path in in_array and in_array[parent_path]:
                    # Increment array counter when closing array element
                    array_counters[parent_path] = array_counters.get(parent_path, 0) + 1
                else:
                    path_stack.pop()
            elif "]" in line and path_stack:
                parent_path = ".".join(path_stack)
                if parent_path in in_array:
                    in_array[parent_path] = False
                path_stack.pop()

    def _get_line_number(self, field_path: str) -> Optional[int]:
        """Get line number for a field path, trying multiple variations.

        Args:
            field_path: JSON field path (e.g., 'stations[0].station_id').

        Returns:
            Line number if found, None otherwise.
        """
        # Try exact match first
        if field_path in self.line_map:
            return self.line_map[field_path]

        # Try with "content." prefix (JSON may have content wrapper)
        prefixed_path = f"content.{field_path}"
        if prefixed_path in self.line_map:
            return self.line_map[prefixed_path]

        # Try the array element itself (e.g., 'resources[1]')
        if "[" in field_path:
            array_element = re.match(r"^([^\[]+\[\d+\])", field_path)
            if array_element:
                element_path = array_element.group(1)
                if element_path in self.line_map:
                    return self.line_map[element_path]
                # Try with content prefix
                prefixed_element = f"content.{element_path}"
                if prefixed_element in self.line_map:
                    return self.line_map[prefixed_element]

        # Try extracting just the field name from paths
        parts = field_path.split(".")
        if parts:
            last_part = parts[-1]
            # Only use this fallback if there's no array index
            if "[" not in field_path and last_part in self.line_map:
                return self.line_map[last_part]

        return None

    @staticmethod
    def check_required_fields(
        item: Dict[str, Any], required_fields: List[str]
    ) -> List[Dict[str, Any]]:
        """Check if all required fields are present in an item.

        Args:
            item: Dictionary to check for required fields.
            required_fields: List of field names that must be present.

        Returns:
            List of error dictionaries for missing fields.
        """
        return [
            {"field": f, "message": f"Missing required field '{f}'"}
            for f in required_fields
            if f not in item
        ]

    def validate_syntax(self, content: Dict[str, Any]) -> List[Dict[str, Any]]:
        """Validate the syntax of scenario content only.

        Args:
            content: Scenario content dictionary to validate.

        Returns:
            List of error dictionaries with field, message, and optional line number.
        """
        errors: List[Dict[str, Any]] = []

        # Validate start_time and end_time exist and are properly formatted
        required_fields = ["start_time", "end_time"]
        for error in self.check_required_fields(content, required_fields):
            line_num = self._get_line_number(error["field"])
            if line_num:
                error["line"] = line_num
            errors.append(error)

        # Validate time format and constraints
        try:
            ScenarioTimes(**content)
        except ValidationError as e:
            for err in e.errors():
                field_path = ".".join(map(str, err["loc"]))
                error_dict: Dict[str, Any] = {
                    "field": field_path,
                    "message": err["msg"],
                }
                line_num = self._get_line_number(field_path)
                if line_num:
                    error_dict["line"] = line_num
                errors.append(error_dict)

        return errors

    def validate_stations(self, stations: List[Dict[str, Any]]) -> List[Dict[str, Any]]:
        """Validate station definitions including IDs, names, and positions.

        Args:
            stations: List of station dictionaries to validate.

        Returns:
            List of error dictionaries for invalid or duplicate stations.
        """
        errors: List[Dict[str, Any]] = []
        seen_ids: Set[int] = set()

        for idx, s in enumerate(stations):
            for error in self.check_required_fields(
                s,
                [
                    "station_id",
                    "station_name",
                    "station_position",
                ],
            ):
                field_path = f"stations[{idx}].{error['field']}"
                line_num = self._get_line_number(field_path)
                if line_num:
                    error["line"] = line_num
                error["field"] = field_path
                errors.append(error)

            station_id_raw: Any = s.get("station_id")
            if isinstance(station_id_raw, int):
                if station_id_raw in seen_ids:
                    field_path = f"stations[{idx}].station_id"
                    dup_error: Dict[str, Any] = {
                        "field": field_path,
                        "message": "Duplicate station ID",
                    }
                    line_num = self._get_line_number(field_path)
                    if line_num:
                        dup_error["line"] = line_num
                    errors.append(dup_error)
                seen_ids.add(station_id_raw)

            try:
                StationValidator(**s)
            except ValidationError as e:
                for err in e.errors():
                    field_name = f"stations[{idx}].{'.'.join(map(str, err['loc']))}"
                    val_error: Dict[str, Any] = {
                        "field": field_name,
                        "message": err["msg"],
                    }
                    line_num = self._get_line_number(field_name)
                    if line_num:
                        val_error["line"] = line_num
                    errors.append(val_error)

        return errors

    def validate_resources(
        self, resources: List[Dict[str, Any]]
    ) -> List[Dict[str, Any]]:
        """Validate resource definitions including IDs and positions.

        Args:
            resources: List of resource dictionaries to validate.

        Returns:
            List of error dictionaries for invalid or duplicate resources.
        """
        errors: List[Dict[str, Any]] = []
        seen_ids: Set[int] = set()

        for idx, r in enumerate(resources):
            for error in self.check_required_fields(
                r, ["resource_id", "resource_position"]
            ):
                field_path = f"resources[{idx}].{error['field']}"
                line_num = self._get_line_number(field_path)
                if line_num:
                    error["line"] = line_num
                error["field"] = field_path
                errors.append(error)

            try:
                validated: ResourceValidator = ResourceValidator(**r)
                if validated.resource_id in seen_ids:
                    field_path = f"resources[{idx}].resource_id"
                    dup_error: Dict[str, Any] = {
                        "field": field_path,
                        "message": "Duplicate resource ID",
                    }
                    line_num = self._get_line_number(field_path)
                    if line_num:
                        dup_error["line"] = line_num
                    errors.append(dup_error)
                seen_ids.add(validated.resource_id)
            except ValidationError as e:
                for err in e.errors():
                    field_name = f"resources[{idx}].{'.'.join(map(str, err['loc']))}"
                    val_error: Dict[str, Any] = {
                        "field": field_name,
                        "message": err["msg"],
                    }
                    line_num = self._get_line_number(field_name)
                    if line_num:
                        val_error["line"] = line_num
                    errors.append(val_error)

        return errors

    def validate_tasks(
        self,
        tasks: List[Dict[str, Any]],
        valid_station_ids: Set[int],
        task_type: str = "tasks",
    ) -> List[Dict[str, Any]]:
        """Validate task definitions and station ID references.

        Args:
            tasks: List of task dictionaries to validate.
            valid_station_ids: Set of valid station IDs for reference checking.
            task_type: Type of task list for error messages
                (e.g., 'initial_tasks', 'scheduled_tasks').

        Returns:
            List of error dictionaries for invalid tasks or station references.
        """
        errors: List[Dict[str, Any]] = []

        for idx, task in enumerate(tasks):
            for error in self.check_required_fields(task, ["station_id"]):
                field_path = f"{task_type}[{idx}].{error['field']}"
                line_num = self._get_line_number(field_path)
                if line_num:
                    error["line"] = line_num
                error["field"] = field_path
                errors.append(error)

            try:
                validated: TaskValidator = TaskValidator(**task)

                if validated.station_id not in valid_station_ids:
                    field_path = f"{task_type}[{idx}].station_id"
                    station_error: Dict[str, Any] = {
                        "field": field_path,
                        "message": f"Station ID {validated.station_id} does not exist",
                    }
                    line_num = self._get_line_number(field_path)
                    if line_num:
                        station_error["line"] = line_num
                    errors.append(station_error)
            except ValidationError as e:
                for err in e.errors():
                    field_name = f"{task_type}[{idx}].{'.'.join(map(str, err['loc']))}"
                    val_error: Dict[str, Any] = {
                        "field": field_name,
                        "message": err["msg"],
                    }
                    line_num = self._get_line_number(field_name)
                    if line_num:
                        val_error["line"] = line_num
                    errors.append(val_error)

        return errors

    def validate_simulation_params(
        self, params: Dict[str, Any]
    ) -> List[Dict[str, Any]]:
        """Validate simulation time parameters.

        Ensures start_time and end_time are valid and that end_time is after start_time.

        Args:
            params: Dictionary containing simulation parameters with
                start_time and end_time.

        Returns:
            List of validation error dictionaries, empty if no errors.
        """
        errors: List[Dict[str, Any]] = []
        start_val: Any = params.get("start_time")
        end_val: Any = params.get("end_time")

        if start_val is not None and end_val is not None:
            try:
                # Parse times using ScenarioTimes validator
                scenario_times = ScenarioTimes(start_time=start_val, end_time=end_val)

                # Validate that end_time is after start_time
                start_daytime = scenario_times.start_time.split(":", 1)
                start_day = start_daytime[0]
                start_time = start_daytime[1]
                end_daytime = scenario_times.end_time.split(":", 1)
                end_day = end_daytime[0]
                end_time = end_daytime[1]
                error = False

                if start_day == end_day:  # if start and end are on the same day
                    st = datetime.strptime(start_time, "%H:%M").time()
                    et = datetime.strptime(end_time, "%H:%M").time()
                    if et <= st:
                        error = True
                else:  # if start and end not on the same day
                    sd = start_day[-1]
                    ed = end_day[-1]
                    if ed < sd:
                        error = True
                if error:
                    time_error: Dict[str, Any] = {
                        "field": "end_time",
                        "message": "end_time must be after start_time",
                    }
                    line_num = self._get_line_number("end_time")
                    if line_num:
                        time_error["line"] = line_num
                    errors.append(time_error)
            except ValidationError as e:
                for err in e.errors():
                    field_path = ".".join(map(str, err["loc"]))
                    val_error: Dict[str, Any] = {
                        "field": field_path,
                        "message": err["msg"],
                    }
                    line_num = self._get_line_number(field_path)
                    if line_num:
                        val_error["line"] = line_num
                    errors.append(val_error)

        return errors

    def validate_all(self, scenario_content: Dict[str, Any]) -> List[Dict[str, Any]]:
        """Validate all aspects of scenario content.

        Args:
            scenario_content: Complete scenario dictionary to validate.

        Returns:
            List of all validation errors found across all validation checks.
        """
        errors: List[Dict[str, Any]] = self.validate_syntax(scenario_content)

        stations: List[Dict[str, Any]] = scenario_content.get("stations", [])
        resources: List[Dict[str, Any]] = scenario_content.get("resources", [])
        initial_tasks: List[Dict[str, Any]] = scenario_content.get("initial_tasks", [])
        scheduled_tasks: List[Dict[str, Any]] = scenario_content.get(
            "scheduled_tasks", []
        )

        errors.extend(self.validate_stations(stations))
        errors.extend(self.validate_resources(resources))

        valid_station_ids: Set[int] = {
            int(s["station_id"]) for s in stations if "station_id" in s
        }
        errors.extend(
            self.validate_tasks(initial_tasks, valid_station_ids, "initial_tasks")
        )
        errors.extend(
            self.validate_tasks(scheduled_tasks, valid_station_ids, "scheduled_tasks")
        )

        errors.extend(self.validate_simulation_params(scenario_content))
        return errors


# ==============================================================================
# Public API - Exceptions
# ==============================================================================


class ScenarioParseError(Exception):
    """Exception raised when scenario parsing/validation fails."""

    def __init__(self, errors: List[Dict[str, Any]]) -> None:
        """Initialize with validation errors.

        Args:
            errors: List of validation error dictionaries.
        """
        self.errors = errors
        error_messages = [
            f"{e.get('field', 'unknown')}: {e.get('message', 'unknown error')}"
            for e in errors
        ]
        super().__init__(f"Scenario validation failed: {'; '.join(error_messages)}")


# ==============================================================================
# Public API - Parser with Integrated Validation
# ==============================================================================


class JsonParseStrategy(BaseParseStrategy):
    """JSON-based scenario parsing strategy with integrated validation.

    This is the main entry point for scenario validation and parsing.
    It combines validation and parsing into a single operation, ensuring
    a single source of truth for what constitutes a valid scenario.
    """

    def __init__(
        self,
        scenario_json: Optional[dict] = None,
        json_string: Optional[str] = None,
    ) -> None:
        """Initialize parser with scenario content and optional JSON string.

        Args:
            scenario_json: Optional dictionary containing scenario configuration.
                If provided, validate() and parse() can be called without parameters.
            json_string: Optional JSON string for line number tracking in errors.
        """
        self.scenario_json = scenario_json
        self._validator = _ScenarioValidator(json_string=json_string)

    def validate(self, scenario_json: Optional[dict] = None) -> List[Dict[str, Any]]:
        """Validate scenario content without parsing.

        Args:
            scenario_json: Optional dictionary containing scenario configuration.
                If not provided, uses the scenario_json from constructor.

        Returns:
            List of validation errors (empty list if valid).

        Raises:
            ValueError: If no scenario_json provided in constructor or parameter.
        """
        json_to_validate = (
            scenario_json if scenario_json is not None else self.scenario_json
        )
        if json_to_validate is None:
            raise ValueError(
                "scenario_json must be provided either in constructor or as parameter"
            )
        content = json_to_validate.get("content", json_to_validate)
        return self._validator.validate_all(content)

    def _time_to_seconds(self, time_str: str) -> int:
        """Convert day-time string to total seconds.

        Converts time format 'dayX:HH:MM' to total seconds from start.

        Args:
            time_str: Time string in format 'dayX:HH:MM' (e.g., 'day1:08:30').

        Returns:
            Total seconds from simulation start.
        """
        daytime_split = time_str.split(":", 1)
        day = daytime_split[0]
        time = daytime_split[1]

        # Extract day number
        day_match = re.match(r"^day(\d+)$", day, re.IGNORECASE)
        day_int = int(day_match.group(1)) - 1  # type: ignore

        # Parse time
        t = datetime.strptime(time, "%H:%M")
        return (day_int * 24) * 3600 + t.hour * 3600 + t.minute * 60

    def parse(self, scenario_json: Optional[dict] = None) -> InputParameter:
        """Parse and validate scenario JSON, returning InputParameter.

        Validates the scenario using Pydantic models before parsing.
        If validation fails, raises ScenarioParseError with details.

        Converts scenario JSON format into an InputParameter object containing
        all simulation configuration including stations, resources, and tasks.

        Args:
            scenario_json: Optional dictionary containing scenario configuration.
                If not provided, uses the scenario_json from constructor.

        Returns:
            InputParameter object with parsed simulation configuration.

        Raises:
            ValueError: If no scenario_json provided in constructor or parameter.
            ScenarioParseError: If scenario validation fails.
        """
        json_to_parse = (
            scenario_json if scenario_json is not None else self.scenario_json
        )
        if json_to_parse is None:
            raise ValueError(
                "scenario_json must be provided either in constructor or as parameter"
            )

        # Extract content (handle both direct content and wrapped format)
        content = json_to_parse.get("content", json_to_parse)

        # Validate before parsing
        validation_errors = self.validate(json_to_parse)
        if validation_errors:
            raise ScenarioParseError(validation_errors)

        # Parse times (validation ensures these are valid)
        start_time = self._time_to_seconds(str(content.get("start_time", "day1:00:00")))
        end_time = self._time_to_seconds(str(content.get("end_time", "day1:00:00")))

        sim_time = end_time - start_time

        # Build stations
        stations: Dict[int, Station] = {}
        for s in content.get("stations", []):
            station_id = int(s["station_id"])
            pos = Position(s.get("station_position", [0, 0]))
            stations[station_id] = Station(
                station_id=station_id,
                name=s.get("station_name", f"Station {station_id}"),
                position=pos,
            )

        # Build resources
        resources: Dict[int, Resource] = {}
        for r in content.get("resources", []):
            rid = int(r["resource_id"])
            pos = Position(r.get("resource_position", [0, 0]))
            resources[rid] = Resource(resource_id=rid, position=pos, task_list=[])

        # Build drivers
        drivers: Dict[int, Driver] = {}
        for d in content.get("drivers", []):
            did = int(d["driver_id"])
            pos = Position(d.get("driver_position", [0, 0]))
            drivers[did] = Driver(driver_id=did, position=pos, task_list=[])

        # Build vehicles
        vehicles: Dict[int, Vehicle] = {}
        for v in content.get("vehicles", []):
            vid = int(v["vehicle_id"])
            battery_count = int(v.get("battery_count", 0))
            vehicles[vid] = Vehicle(vehicle_id=vid, battery_count=battery_count)

        # Build tasks
        tasks: Dict[int, BatterySwapTask] = {}
        task_id_counter = 1

        # Initial tasks
        for t in content.get("initial_tasks", []):
            tid = task_id_counter
            task_id_counter += 1

            station_ref = stations[int(t["station_id"])]
            task = BatterySwapTask(task_id=tid, station=station_ref, spawn_delay=0.0)
            tasks[tid] = task
            station_ref.add_task(task)

            # Assign to resource if specified
            assigned_did = t.get("assigned_driver_id")
            if assigned_did is not None:
                drivers[int(assigned_did)].assign_task(task)

        # Scheduled tasks
        for t in content.get("scheduled_tasks", []):
            tid = task_id_counter
            task_id_counter += 1

            station_ref = stations[int(t["station_id"])]
            raw_time = t.get("time", 0)
            if isinstance(raw_time, str):
                delay = self._time_to_seconds(raw_time) - start_time
            else:
                delay = int(raw_time)

            task = BatterySwapTask(task_id=tid, station=station_ref, spawn_delay=delay)
            tasks[tid] = task
            station_ref.add_task(task)

        params = InputParameter(
            station_entities=stations,
            resource_entities=resources,
            driver_entities=drivers,
            task_entities=tasks,
            real_time_factor=content.get("real_time_factor", 1.0),
            key_frame_freq=content.get("key_frame_freq", 20),
            sim_time=sim_time,
            start_time=start_time,
        )

        return params
