#!/bin/bash
# Archive creation script for VeloSim deployment
# Generated by Ansible

set -e

PLAYBOOK_DIR="$1"
ARCHIVE_PATH="$2"

cd "$PLAYBOOK_DIR/../"

tar --exclude-from=.rsyncignore \
    --exclude='.git' \
    --exclude='node_modules' \
    --exclude='__pycache__' \
    --exclude='*.pyc' \
    --exclude='.env*' \
    --exclude='.vscode' \
    --exclude='.idea' \
    --exclude='*.log' \
    --exclude='logs' \
    --exclude='.DS_Store' \
    --exclude='._*' \
    --exclude='.AppleDouble' \
    --exclude='.LSOverride' \
    --exclude='ansible/.vagrant' \
    --exclude='ansible/facts_cache' \
    --exclude='osrm-data' \
    --exclude='*.egg-info' \
    --exclude='.pytest_cache' \
    --exclude='coverage.html' \
    --exclude='.coverage' \
    -czf "$ARCHIVE_PATH" .

echo "Archive created: $ARCHIVE_PATH"