#!/bin/bash
# Set file permissions script for VeloSim
# Generated by Ansible

set -e

APP_DIR="$1"

echo "Setting file permissions in $APP_DIR/source"

find "$APP_DIR/source" -name "*.sh" -type f -exec chmod +x {} \;
find "$APP_DIR/source" -name "*.py" -type f -exec chmod 644 {} \;
find "$APP_DIR/source" -type d -exec chmod 755 {} \;

echo "File permissions set successfully"